// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// correlation_gradient_cpp
NumericVector correlation_gradient_cpp(const NumericVector& img_4d, const NumericVector& brain_mask);
RcppExport SEXP _neurocluster_correlation_gradient_cpp(SEXP img_4dSEXP, SEXP brain_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type img_4d(img_4dSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type brain_mask(brain_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_gradient_cpp(img_4d, brain_mask));
    return rcpp_result_gen;
END_RCPP
}
// heat_kernel
double heat_kernel(NumericVector x1, NumericVector x2, double sigma);
RcppExport SEXP _neurocluster_heat_kernel(SEXP x1SEXP, SEXP x2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(heat_kernel(x1, x2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// normalized_heat_kernel
double normalized_heat_kernel(NumericVector x1, NumericVector x2, double sigma);
RcppExport SEXP _neurocluster_normalized_heat_kernel(SEXP x1SEXP, SEXP x2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(normalized_heat_kernel(x1, x2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// compute_scores
NumericVector compute_scores(IntegerVector curclus, NumericMatrix coords, NumericMatrix data_centroids, NumericMatrix coord_centroids, NumericMatrix data, double sigma1, double sigma2);
RcppExport SEXP _neurocluster_compute_scores(SEXP curclusSEXP, SEXP coordsSEXP, SEXP data_centroidsSEXP, SEXP coord_centroidsSEXP, SEXP dataSEXP, SEXP sigma1SEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type curclus(curclusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data_centroids(data_centroidsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coord_centroids(coord_centroidsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_scores(curclus, coords, data_centroids, coord_centroids, data, sigma1, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// best_candidate
IntegerVector best_candidate(List candidates, IntegerVector curclus, NumericMatrix coords, NumericMatrix data_centroids, NumericMatrix coord_centroids, NumericMatrix data, double sigma1, double sigma2, double alpha);
RcppExport SEXP _neurocluster_best_candidate(SEXP candidatesSEXP, SEXP curclusSEXP, SEXP coordsSEXP, SEXP data_centroidsSEXP, SEXP coord_centroidsSEXP, SEXP dataSEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type curclus(curclusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data_centroids(data_centroidsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coord_centroids(coord_centroidsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(best_candidate(candidates, curclus, coords, data_centroids, coord_centroids, data, sigma1, sigma2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// find_candidates
List find_candidates(IntegerMatrix nn_index, NumericMatrix nn_dist, IntegerVector curclus, double dthresh);
RcppExport SEXP _neurocluster_find_candidates(SEXP nn_indexSEXP, SEXP nn_distSEXP, SEXP curclusSEXP, SEXP dthreshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_index(nn_indexSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nn_dist(nn_distSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type curclus(curclusSEXP);
    Rcpp::traits::input_parameter< double >::type dthresh(dthreshSEXP);
    rcpp_result_gen = Rcpp::wrap(find_candidates(nn_index, nn_dist, curclus, dthresh));
    return rcpp_result_gen;
END_RCPP
}
// update_centroid_online
List update_centroid_online(const List& centroid, const NumericVector& x_i, const NumericVector& c_i);
RcppExport SEXP _neurocluster_update_centroid_online(SEXP centroidSEXP, SEXP x_iSEXP, SEXP c_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type centroid(centroidSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_i(x_iSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type c_i(c_iSEXP);
    rcpp_result_gen = Rcpp::wrap(update_centroid_online(centroid, x_i, c_i));
    return rcpp_result_gen;
END_RCPP
}
// snic_main
IntegerVector snic_main(IntegerVector L_data, const IntegerVector& mask, const NumericMatrix centroids, const IntegerVector centroid_idx, const IntegerMatrix valid_coords, const NumericMatrix norm_coords, const NumericMatrix& vecmat, int K, double s, double compactness, IntegerVector mask_lookup_data);
RcppExport SEXP _neurocluster_snic_main(SEXP L_dataSEXP, SEXP maskSEXP, SEXP centroidsSEXP, SEXP centroid_idxSEXP, SEXP valid_coordsSEXP, SEXP norm_coordsSEXP, SEXP vecmatSEXP, SEXP KSEXP, SEXP sSEXP, SEXP compactnessSEXP, SEXP mask_lookup_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type L_data(L_dataSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type centroids(centroidsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type centroid_idx(centroid_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix >::type valid_coords(valid_coordsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type norm_coords(norm_coordsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type vecmat(vecmatSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type compactness(compactnessSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask_lookup_data(mask_lookup_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(snic_main(L_data, mask, centroids, centroid_idx, valid_coords, norm_coords, vecmat, K, s, compactness, mask_lookup_data));
    return rcpp_result_gen;
END_RCPP
}
// compute_boundaryscore_3d_cpp
IntegerVector compute_boundaryscore_3d_cpp(IntegerVector volume, IntegerVector mask);
RcppExport SEXP _neurocluster_compute_boundaryscore_3d_cpp(SEXP volumeSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type volume(volumeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_boundaryscore_3d_cpp(volume, mask));
    return rcpp_result_gen;
END_RCPP
}
// detect_boundaries_2d_cpp
IntegerVector detect_boundaries_2d_cpp(IntegerVector volume, IntegerVector mask);
RcppExport SEXP _neurocluster_detect_boundaries_2d_cpp(SEXP volumeSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type volume(volumeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_boundaries_2d_cpp(volume, mask));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_correlation_gradient_module();

static const R_CallMethodDef CallEntries[] = {
    {"_neurocluster_correlation_gradient_cpp", (DL_FUNC) &_neurocluster_correlation_gradient_cpp, 2},
    {"_neurocluster_heat_kernel", (DL_FUNC) &_neurocluster_heat_kernel, 3},
    {"_neurocluster_normalized_heat_kernel", (DL_FUNC) &_neurocluster_normalized_heat_kernel, 3},
    {"_neurocluster_compute_scores", (DL_FUNC) &_neurocluster_compute_scores, 7},
    {"_neurocluster_best_candidate", (DL_FUNC) &_neurocluster_best_candidate, 9},
    {"_neurocluster_find_candidates", (DL_FUNC) &_neurocluster_find_candidates, 4},
    {"_neurocluster_update_centroid_online", (DL_FUNC) &_neurocluster_update_centroid_online, 3},
    {"_neurocluster_snic_main", (DL_FUNC) &_neurocluster_snic_main, 11},
    {"_neurocluster_compute_boundaryscore_3d_cpp", (DL_FUNC) &_neurocluster_compute_boundaryscore_3d_cpp, 2},
    {"_neurocluster_detect_boundaries_2d_cpp", (DL_FUNC) &_neurocluster_detect_boundaries_2d_cpp, 2},
    {"_rcpp_module_boot_correlation_gradient_module", (DL_FUNC) &_rcpp_module_boot_correlation_gradient_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_neurocluster(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
