# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

correlation_gradient_cpp <- function(img_4d, brain_mask) {
    .Call('_neurocluster_correlation_gradient_cpp', PACKAGE = 'neurocluster', img_4d, brain_mask)
}

heat_kernel <- function(x1, x2, sigma) {
    .Call('_neurocluster_heat_kernel', PACKAGE = 'neurocluster', x1, x2, sigma)
}

normalized_heat_kernel <- function(x1, x2, sigma) {
    .Call('_neurocluster_normalized_heat_kernel', PACKAGE = 'neurocluster', x1, x2, sigma)
}

compute_scores <- function(curclus, coords, data_centroids, coord_centroids, data, sigma1, sigma2) {
    .Call('_neurocluster_compute_scores', PACKAGE = 'neurocluster', curclus, coords, data_centroids, coord_centroids, data, sigma1, sigma2)
}

best_candidate <- function(candidates, curclus, coords, data_centroids, coord_centroids, data, sigma1, sigma2, alpha) {
    .Call('_neurocluster_best_candidate', PACKAGE = 'neurocluster', candidates, curclus, coords, data_centroids, coord_centroids, data, sigma1, sigma2, alpha)
}

find_candidates <- function(nn_index, nn_dist, curclus, dthresh) {
    .Call('_neurocluster_find_candidates', PACKAGE = 'neurocluster', nn_index, nn_dist, curclus, dthresh)
}

update_centroid_online <- function(centroid, x_i, c_i) {
    .Call('_neurocluster_update_centroid_online', PACKAGE = 'neurocluster', centroid, x_i, c_i)
}

snic_main <- function(L_data, mask, centroids, centroid_idx, valid_coords, norm_coords, vecmat, K, s, compactness, mask_lookup_data) {
    .Call('_neurocluster_snic_main', PACKAGE = 'neurocluster', L_data, mask, centroids, centroid_idx, valid_coords, norm_coords, vecmat, K, s, compactness, mask_lookup_data)
}

compute_boundaryscore_3d_cpp <- function(volume, mask) {
    .Call('_neurocluster_compute_boundaryscore_3d_cpp', PACKAGE = 'neurocluster', volume, mask)
}

detect_boundaries_2d_cpp <- function(volume, mask) {
    .Call('_neurocluster_detect_boundaries_2d_cpp', PACKAGE = 'neurocluster', volume, mask)
}

